package com.gmall.data.common.entity.ods.gmall2021

import com.gmall.data.common.entity.ods
import com.gmall.data.common.entity.ods.OdsModel
import com.gmall.data.common.entity.ods.SqlType.SqlType
import scala.collection.mutable

// IMPORTANT!!! Don't do any changes, this is auto-generated by OdsModelGenerator
class ActivityInfo extends OdsModel {
  override var database: String            = _
  override var table   : String            = _
  override var ts      : Long              = _
  override var sqlType : ods.SqlType.Value = _
  override var old     : mutable.Map[String, String] = _
  var id: String = _
var activity_name: String = _
var activity_type: String = _
var activity_desc: String = _
var start_time: String = _
var end_time: String = _
var create_time: String = _

  def this(database: String, table: String, sqlType: SqlType, ts: Long, old: mutable.Map[String, String]) {
    this()
    this.database = database
    this.table = table
    this.sqlType = sqlType
    this.ts = ts
    this.old = old
  }

  override def toString = s"ActivityInfo(database=$database, table=$table, sqlType=$sqlType, ts=$ts, old=$old, id=${id}, activity_name=${activity_name}, activity_type=${activity_type}, activity_desc=${activity_desc}, start_time=${start_time}, end_time=${end_time}, create_time=${create_time})"

}
