package com.gmall.data.common.entity.ods.gmall2021

import com.gmall.data.common.entity.ods
import com.gmall.data.common.entity.ods.OdsModel
import com.gmall.data.common.entity.ods.SqlType.SqlType
import scala.collection.mutable

// IMPORTANT!!! Don't do any changes, this is auto-generated by OdsModelGenerator
class ActivityRule extends OdsModel {
  override var database: String            = _
  override var table   : String            = _
  override var ts      : Long              = _
  override var sqlType : ods.SqlType.Value = _
  override var old     : mutable.Map[String, String] = _
  var id: String = _
var activity_id: String = _
var activity_type: String = _
var condition_amount: String = _
var condition_num: String = _
var benefit_amount: String = _
var benefit_discount: String = _
var benefit_level: String = _

  def this(database: String, table: String, sqlType: SqlType, ts: Long, old: mutable.Map[String, String]) {
    this()
    this.database = database
    this.table = table
    this.sqlType = sqlType
    this.ts = ts
    this.old = old
  }

  override def toString = s"ActivityRule(database=$database, table=$table, sqlType=$sqlType, ts=$ts, old=$old, id=${id}, activity_id=${activity_id}, activity_type=${activity_type}, condition_amount=${condition_amount}, condition_num=${condition_num}, benefit_amount=${benefit_amount}, benefit_discount=${benefit_discount}, benefit_level=${benefit_level})"

}
