package com.gmall.data.common.entity.ods.gmall2021

import com.gmall.data.common.entity.ods
import com.gmall.data.common.entity.ods.OdsModel
import com.gmall.data.common.entity.ods.SqlType.SqlType
import scala.collection.mutable

// IMPORTANT!!! Don't do any changes, this is auto-generated by OdsModelGenerator
class CartInfo extends OdsModel {
  override var database: String            = _
  override var table   : String            = _
  override var ts      : Long              = _
  override var sqlType : ods.SqlType.Value = _
  override var old     : mutable.Map[String, String] = _
  var id: String = _
var user_id: String = _
var sku_id: String = _
var cart_price: String = _
var sku_num: String = _
var img_url: String = _
var sku_name: String = _
var is_checked: String = _
var create_time: String = _
var operate_time: String = _
var is_ordered: String = _
var order_time: String = _
var source_type: String = _
var source_id: String = _

  def this(database: String, table: String, sqlType: SqlType, ts: Long, old: mutable.Map[String, String]) {
    this()
    this.database = database
    this.table = table
    this.sqlType = sqlType
    this.ts = ts
    this.old = old
  }

  override def toString = s"CartInfo(database=$database, table=$table, sqlType=$sqlType, ts=$ts, old=$old, id=${id}, user_id=${user_id}, sku_id=${sku_id}, cart_price=${cart_price}, sku_num=${sku_num}, img_url=${img_url}, sku_name=${sku_name}, is_checked=${is_checked}, create_time=${create_time}, operate_time=${operate_time}, is_ordered=${is_ordered}, order_time=${order_time}, source_type=${source_type}, source_id=${source_id})"

}
