package com.gmall.data.common.entity.ods.gmall2021

import com.gmall.data.common.entity.ods
import com.gmall.data.common.entity.ods.OdsModel
import com.gmall.data.common.entity.ods.SqlType.SqlType
import scala.collection.mutable

// IMPORTANT!!! Don't do any changes, this is auto-generated by OdsModelGenerator
class CouponInfo extends OdsModel {
  override var database: String            = _
  override var table   : String            = _
  override var ts      : Long              = _
  override var sqlType : ods.SqlType.Value = _
  override var old     : mutable.Map[String, String] = _
  var id: String = _
var coupon_name: String = _
var coupon_type: String = _
var condition_amount: String = _
var condition_num: String = _
var activity_id: String = _
var benefit_amount: String = _
var benefit_discount: String = _
var create_time: String = _
var range_type: String = _
var limit_num: String = _
var taken_count: String = _
var start_time: String = _
var end_time: String = _
var operate_time: String = _
var expire_time: String = _
var range_desc: String = _

  def this(database: String, table: String, sqlType: SqlType, ts: Long, old: mutable.Map[String, String]) {
    this()
    this.database = database
    this.table = table
    this.sqlType = sqlType
    this.ts = ts
    this.old = old
  }

  override def toString = s"CouponInfo(database=$database, table=$table, sqlType=$sqlType, ts=$ts, old=$old, id=${id}, coupon_name=${coupon_name}, coupon_type=${coupon_type}, condition_amount=${condition_amount}, condition_num=${condition_num}, activity_id=${activity_id}, benefit_amount=${benefit_amount}, benefit_discount=${benefit_discount}, create_time=${create_time}, range_type=${range_type}, limit_num=${limit_num}, taken_count=${taken_count}, start_time=${start_time}, end_time=${end_time}, operate_time=${operate_time}, expire_time=${expire_time}, range_desc=${range_desc})"

}
