package com.gmall.data.common.entity.ods.gmall2021

import com.gmall.data.common.entity.ods
import com.gmall.data.common.entity.ods.OdsModel
import com.gmall.data.common.entity.ods.SqlType.SqlType
import scala.collection.mutable

// IMPORTANT!!! Don't do any changes, this is auto-generated by OdsModelGenerator
class OrderDetail extends OdsModel {
  override var database: String            = _
  override var table   : String            = _
  override var ts      : Long              = _
  override var sqlType : ods.SqlType.Value = _
  override var old     : mutable.Map[String, String] = _
  var id: String = _
var order_id: String = _
var sku_id: String = _
var sku_name: String = _
var img_url: String = _
var order_price: String = _
var sku_num: String = _
var create_time: String = _
var source_type: String = _
var source_id: String = _
var split_total_amount: String = _
var split_activity_amount: String = _
var split_coupon_amount: String = _

  def this(database: String, table: String, sqlType: SqlType, ts: Long, old: mutable.Map[String, String]) {
    this()
    this.database = database
    this.table = table
    this.sqlType = sqlType
    this.ts = ts
    this.old = old
  }

  override def toString = s"OrderDetail(database=$database, table=$table, sqlType=$sqlType, ts=$ts, old=$old, id=${id}, order_id=${order_id}, sku_id=${sku_id}, sku_name=${sku_name}, img_url=${img_url}, order_price=${order_price}, sku_num=${sku_num}, create_time=${create_time}, source_type=${source_type}, source_id=${source_id}, split_total_amount=${split_total_amount}, split_activity_amount=${split_activity_amount}, split_coupon_amount=${split_coupon_amount})"

}
