package com.gmall.data.common.entity.ods.gmall2021

import com.gmall.data.common.entity.ods
import com.gmall.data.common.entity.ods.OdsModel
import com.gmall.data.common.entity.ods.SqlType.SqlType
import scala.collection.mutable

// IMPORTANT!!! Don't do any changes, this is auto-generated by OdsModelGenerator
class OrderRefundInfo extends OdsModel {
  override var database: String            = _
  override var table   : String            = _
  override var ts      : Long              = _
  override var sqlType : ods.SqlType.Value = _
  override var old     : mutable.Map[String, String] = _
  var id: String = _
var user_id: String = _
var order_id: String = _
var sku_id: String = _
var refund_type: String = _
var refund_num: String = _
var refund_amount: String = _
var refund_reason_type: String = _
var refund_reason_txt: String = _
var refund_status: String = _
var create_time: String = _

  def this(database: String, table: String, sqlType: SqlType, ts: Long, old: mutable.Map[String, String]) {
    this()
    this.database = database
    this.table = table
    this.sqlType = sqlType
    this.ts = ts
    this.old = old
  }

  override def toString = s"OrderRefundInfo(database=$database, table=$table, sqlType=$sqlType, ts=$ts, old=$old, id=${id}, user_id=${user_id}, order_id=${order_id}, sku_id=${sku_id}, refund_type=${refund_type}, refund_num=${refund_num}, refund_amount=${refund_amount}, refund_reason_type=${refund_reason_type}, refund_reason_txt=${refund_reason_txt}, refund_status=${refund_status}, create_time=${create_time})"

}
