package com.gmall.data.common.entity.ods.gmall2021

import com.gmall.data.common.entity.ods
import com.gmall.data.common.entity.ods.OdsModel
import com.gmall.data.common.entity.ods.SqlType.SqlType
import scala.collection.mutable

// IMPORTANT!!! Don't do any changes, this is auto-generated by OdsModelGenerator
class OrderInfo extends OdsModel {
  override var database: String            = _
  override var table   : String            = _
  override var ts      : Long              = _
  override var sqlType : ods.SqlType.Value = _
  override var old     : mutable.Map[String, String] = _
  var id: String = _
var consignee: String = _
var consignee_tel: String = _
var total_amount: String = _
var order_status: String = _
var user_id: String = _
var payment_way: String = _
var delivery_address: String = _
var order_comment: String = _
var out_trade_no: String = _
var trade_body: String = _
var create_time: String = _
var operate_time: String = _
var expire_time: String = _
var process_status: String = _
var tracking_no: String = _
var parent_order_id: String = _
var img_url: String = _
var province_id: String = _
var activity_reduce_amount: String = _
var coupon_reduce_amount: String = _
var original_total_amount: String = _
var feight_fee: String = _
var feight_fee_reduce: String = _
var refundable_time: String = _

  def this(database: String, table: String, sqlType: SqlType, ts: Long, old: mutable.Map[String, String]) {
    this()
    this.database = database
    this.table = table
    this.sqlType = sqlType
    this.ts = ts
    this.old = old
  }

  override def toString = s"OrderInfo(database=$database, table=$table, sqlType=$sqlType, ts=$ts, old=$old, id=${id}, consignee=${consignee}, consignee_tel=${consignee_tel}, total_amount=${total_amount}, order_status=${order_status}, user_id=${user_id}, payment_way=${payment_way}, delivery_address=${delivery_address}, order_comment=${order_comment}, out_trade_no=${out_trade_no}, trade_body=${trade_body}, create_time=${create_time}, operate_time=${operate_time}, expire_time=${expire_time}, process_status=${process_status}, tracking_no=${tracking_no}, parent_order_id=${parent_order_id}, img_url=${img_url}, province_id=${province_id}, activity_reduce_amount=${activity_reduce_amount}, coupon_reduce_amount=${coupon_reduce_amount}, original_total_amount=${original_total_amount}, feight_fee=${feight_fee}, feight_fee_reduce=${feight_fee_reduce}, refundable_time=${refundable_time})"

}
