package com.gmall.data.common.entity.ods.gmall2021

import com.gmall.data.common.entity.ods
import com.gmall.data.common.entity.ods.OdsModel
import com.gmall.data.common.entity.ods.SqlType.SqlType
import scala.collection.mutable

// IMPORTANT!!! Don't do any changes, this is auto-generated by OdsModelGenerator
class RefundPayment extends OdsModel {
  override var database: String            = _
  override var table   : String            = _
  override var ts      : Long              = _
  override var sqlType : ods.SqlType.Value = _
  override var old     : mutable.Map[String, String] = _
  var id: String = _
var out_trade_no: String = _
var order_id: String = _
var sku_id: String = _
var payment_type: String = _
var trade_no: String = _
var total_amount: String = _
var subject: String = _
var refund_status: String = _
var create_time: String = _
var callback_time: String = _
var callback_content: String = _

  def this(database: String, table: String, sqlType: SqlType, ts: Long, old: mutable.Map[String, String]) {
    this()
    this.database = database
    this.table = table
    this.sqlType = sqlType
    this.ts = ts
    this.old = old
  }

  override def toString = s"RefundPayment(database=$database, table=$table, sqlType=$sqlType, ts=$ts, old=$old, id=${id}, out_trade_no=${out_trade_no}, order_id=${order_id}, sku_id=${sku_id}, payment_type=${payment_type}, trade_no=${trade_no}, total_amount=${total_amount}, subject=${subject}, refund_status=${refund_status}, create_time=${create_time}, callback_time=${callback_time}, callback_content=${callback_content})"

}
