package com.gmall.data.common.entity.ods.gmall2021

import com.gmall.data.common.entity.ods
import com.gmall.data.common.entity.ods.OdsModel
import com.gmall.data.common.entity.ods.SqlType.SqlType
import scala.collection.mutable

// IMPORTANT!!! Don't do any changes, this is auto-generated by OdsModelGenerator
class SeckillGoods extends OdsModel {
  override var database: String            = _
  override var table   : String            = _
  override var ts      : Long              = _
  override var sqlType : ods.SqlType.Value = _
  override var old     : mutable.Map[String, String] = _
  var id: String = _
var spu_id: String = _
var sku_id: String = _
var sku_name: String = _
var sku_default_img: String = _
var price: String = _
var cost_price: String = _
var create_time: String = _
var check_time: String = _
var status: String = _
var start_time: String = _
var end_time: String = _
var num: String = _
var stock_count: String = _
var sku_desc: String = _

  def this(database: String, table: String, sqlType: SqlType, ts: Long, old: mutable.Map[String, String]) {
    this()
    this.database = database
    this.table = table
    this.sqlType = sqlType
    this.ts = ts
    this.old = old
  }

  override def toString = s"SeckillGoods(database=$database, table=$table, sqlType=$sqlType, ts=$ts, old=$old, id=${id}, spu_id=${spu_id}, sku_id=${sku_id}, sku_name=${sku_name}, sku_default_img=${sku_default_img}, price=${price}, cost_price=${cost_price}, create_time=${create_time}, check_time=${check_time}, status=${status}, start_time=${start_time}, end_time=${end_time}, num=${num}, stock_count=${stock_count}, sku_desc=${sku_desc})"

}
