package com.gmall.data.common.entity.ods.gmall2021

import com.gmall.data.common.entity.ods
import com.gmall.data.common.entity.ods.OdsModel
import com.gmall.data.common.entity.ods.SqlType.SqlType
import scala.collection.mutable

// IMPORTANT!!! Don't do any changes, this is auto-generated by OdsModelGenerator
class UserInfo extends OdsModel {
  override var database: String            = _
  override var table   : String            = _
  override var ts      : Long              = _
  override var sqlType : ods.SqlType.Value = _
  override var old     : mutable.Map[String, String] = _
  var id: String = _
var login_name: String = _
var nick_name: String = _
var passwd: String = _
var name: String = _
var phone_num: String = _
var email: String = _
var head_img: String = _
var user_level: String = _
var birthday: String = _
var gender: String = _
var create_time: String = _
var operate_time: String = _
var status: String = _

  def this(database: String, table: String, sqlType: SqlType, ts: Long, old: mutable.Map[String, String]) {
    this()
    this.database = database
    this.table = table
    this.sqlType = sqlType
    this.ts = ts
    this.old = old
  }

  override def toString = s"UserInfo(database=$database, table=$table, sqlType=$sqlType, ts=$ts, old=$old, id=${id}, login_name=${login_name}, nick_name=${nick_name}, passwd=${passwd}, name=${name}, phone_num=${phone_num}, email=${email}, head_img=${head_img}, user_level=${user_level}, birthday=${birthday}, gender=${gender}, create_time=${create_time}, operate_time=${operate_time}, status=${status})"

}
