package com.gmall.data.common.entity.ods.gmall2021

import com.gmall.data.common.entity.ods
import com.gmall.data.common.entity.ods.OdsModel
import com.gmall.data.common.entity.ods.SqlType.SqlType
import scala.collection.mutable

// IMPORTANT!!! Don't do any changes, this is auto-generated by OdsModelGenerator
class WareOrderTask extends OdsModel {
  override var database: String            = _
  override var table   : String            = _
  override var ts      : Long              = _
  override var sqlType : ods.SqlType.Value = _
  override var old     : mutable.Map[String, String] = _
  var id: String = _
var order_id: String = _
var consignee: String = _
var consignee_tel: String = _
var delivery_address: String = _
var order_comment: String = _
var payment_way: String = _
var task_status: String = _
var order_body: String = _
var tracking_no: String = _
var create_time: String = _
var ware_id: String = _
var task_comment: String = _

  def this(database: String, table: String, sqlType: SqlType, ts: Long, old: mutable.Map[String, String]) {
    this()
    this.database = database
    this.table = table
    this.sqlType = sqlType
    this.ts = ts
    this.old = old
  }

  override def toString = s"WareOrderTask(database=$database, table=$table, sqlType=$sqlType, ts=$ts, old=$old, id=${id}, order_id=${order_id}, consignee=${consignee}, consignee_tel=${consignee_tel}, delivery_address=${delivery_address}, order_comment=${order_comment}, payment_way=${payment_way}, task_status=${task_status}, order_body=${order_body}, tracking_no=${tracking_no}, create_time=${create_time}, ware_id=${ware_id}, task_comment=${task_comment})"

}
